### ISSUE TITLE
Don't work `<q-btn icon="create">New item</q-btn>`

### ISSUE THREAD

**Issue by thearabbit** [quasarframework/quasar-template-meteor#13]
I tried to use `<q-btn icon="create">New item</q-btn>`.
But don't work, why?

**Comment by rstoenescu** [comment]
Meteor template is not yet compatible with v0.14. Use v0.13 while we make it work with v0.14. Thank you for your patience.

**Comment by thearabbit** [comment]
Wating for support `Meteor`!
I love `Quasar`.
