### ISSUE TITLE
Quasar Discord > Meteor channel

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar-template-meteor#19]
Hi @mwarren2 ,

Sorry for opening an issue. Didn't know how to contact you otherwise. Please close it as soon as you read it.

I've switched Quasar's chat from Gitter to Discord and what I want to ask you is: would you like a channel specifically for Meteor?

Let me know or contact me directly on Discord (https://discord.gg/5TDhbDg)

-Razvan Stoenescu

**Comment by mwarren2** [comment]
@rstoenescu Can't seem to work out how to talk to you on Discord.
Sorry for the slow reply, but I wanted to think about it.

My admiration for you and your framework is unbounded, and I mean it, but I have to say no.
I'm not getting through my personal goals fast enough at the moment, and I fear the distraction.
Thank you for asking me

**Comment by mwarren2** [comment]
@rstoenescu P.S. Actually all that matters is that it isn't connected to me personally. A meteor channel would probably good in the sense that there seems to be a lot of interest from Meteor users in your framework.
I just can't commit to running it myself.

**Comment by rstoenescu** [comment]
It isn't connected to you personally. It's just a channel for Meteor connected to this repo. People may ask questions. You can answer them whenever you wish and if you wish. Just helps smooth things out. Nothing more.

**Comment by mwarren2** [comment]
That's fine. 
I'm sure it would speed up acceptance for Quasar.

Please go ahead.

**Comment by rstoenescu** [comment]
Already created it. https://discord.gg/5TDhbDg > #meteor
