### ISSUE TITLE
Cannot find module '/node_modules/quasar-framework/dist/quasar.mat.common.js'

### ISSUE THREAD

**Issue by thearabbit** [quasarframework/quasar-template-meteor#20]
After pull last, and `update npm and meteor`.
Get error

![image](https://user-images.githubusercontent.com/4495160/36933561-b68754f2-1f0d-11e8-92d9-0f41d684897a.png)

**Comment by mwarren2** [comment]
Did you call
`npm run transpile`?

**Comment by thearabbit** [comment]
Thanks I will check readme again

**Comment by thearabbit** [comment]
Now it work fine
👍
