### ISSUE TITLE
transpile.bat is empty

### ISSUE THREAD

**Issue by Noboxulus** [quasarframework/quasar-template-meteor#21]
As says the title, the bat file doesn't contain the commands required for windows users to transpile.

It should contain the commands written by [antoninadert](https://github.com/antoninadert):

> move .\.babelrc.RENAMED .\.babelrc && .\node_modules\.bin\babel node_modules\quasar-framework\dist\quasar.ios.esm.js --out-file node_modules\quasar-framework\dist\quasar.ios.common.js && .\node_modules\.bin\babel node_modules\quasar-framework\dist\quasar.mat.esm.js --out-file node_modules\quasar-framework\dist\quasar.mat.common.js && move .\.babelrc .\.babelrc.RENAMED 

Quoted from the txt file posted by [antoninadert](https://github.com/antoninadert):
![image](https://user-images.githubusercontent.com/19311003/37327557-cab04e90-26d1-11e8-8209-bb3d5f60539a.png)

**Comment by mwarren2** [comment]
Thanks.
I've fixed it
