### ISSUE TITLE
Notify plugin not working

### ISSUE THREAD

**Issue by antoineschaller** [quasarframework/quasar-template-meteor#22]
Hi,

I can get Notify to work with the current version.
I installed it using 
`Vue.use(Quasar, {plugins: {Notify}})` and it indicates it is installed 
<img width="331" alt="screen shot 2018-03-27 at 17 57 50" src="https://user-images.githubusercontent.com/1187121/38139229-d067b43a-342e-11e8-906f-6a08e6295019.png">
but nothing happens on Notify.create('Message') calls and `this.$q.notify('Message')` returns the `Uncaught (in promise) TypeError: this.$q.notify is not a function` error.

Does someone have an idea where to look to fix this?

**Comment by rstoenescu** [comment]
I think Quasar needs to be updated to latest 0.15.10

**Comment by mwarren2** [comment]
Ok, will update soonest, and then try it out as well.

I'll be in touch asap

**Comment by mwarren2** [comment]
I've updated to 0.15.10 
Hope it helps.

**Comment by antoineschaller** [comment]
@mwarren2 @rstoenescu awesome this fixes it! thanks for your quick help ;)
