### ISSUE TITLE
Blank page when I run using the latest version of this template (as of 15-june-2018)

### ISSUE THREAD

**Issue by Noboxulus** [quasarframework/quasar-template-meteor#25]
I face the issue when I run meteor on this project, i.e. starting the server with the command `meteor`.

I tried all the below methods to no avail:
1.  `meteor update` and `meteor update --patch` in the template folder
2. Removing the .local folder and running `meteor`
3. Removing node_modules folder and running `meteor npm install`
4. Removing everything and cloning the git repo.
5. Upgrading meteor (my meteor was already the latest so this doesn't do anything.)

Below is the image snippet of the errors in my browser's console:
![image](https://user-images.githubusercontent.com/19311003/41460042-f2fe406a-70bd-11e8-81ff-539da6adaceb.png)

> * modules.js:20871 Uncaught SyntaxError: Unexpected token export
> * babel-runtime.js?hash=ad2513735fa8d9d75196ab30ea0bd927586919be:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
>   * at babel-runtime.js?hash=ad2513735fa8d9d75196ab30ea0bd927586919be:17
>   * at babel-runtime.js?hash=ad2513735fa8d9d75196ab30ea0bd927586919be:149
> * promise.js?hash=badbb15e6daa4c8fb4dcd6049286a198af5008b4:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
>   * at promise.js?hash=badbb15e6daa4c8fb4dcd6049286a198af5008b4:17
>   * at promise.js?hash=badbb15e6daa4c8fb4dcd6049286a198af5008b4:161
> * url.js?hash=b17f76f223e6c33b3a66db77c8e2fe550a0bad4d:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
>   * at url.js?hash=b17f76f223e6c33b3a66db77c8e2fe550a0bad4d:17
>   * at url.js?hash=b17f76f223e6c33b3a66db77c8e2fe550a0bad4d:117
> * http.js?hash=d3dd208935f8ca87ff86948a53498046333fdb3b:17 Uncaught TypeError: Cannot read property 'URL' of undefined
>   * at http.js?hash=d3dd208935f8ca87ff86948a53498046333fdb3b:17
>   * at http.js?hash=d3dd208935f8ca87ff86948a53498046333fdb3b:363
> * dynamic-import.js?hash=87f0db8f0a341c7a9f6962f1accefd2d37498f58:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
>   * at dynamic-import.js?hash=87f0db8f0a341c7a9f6962f1accefd2d37498f58:17
>   * at dynamic-import.js?hash=87f0db8f0a341c7a9f6962f1accefd2d37498f58:521
> * ecmascript-runtime-client.js?hash=3755b87a9db33c177a60cfa7cbf41e1d9033df6f:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
>   * at ecmascript-runtime-client.js?hash=3755b87a9db33c177a60cfa7cbf41e1d9033df6f:17
>   * at ecmascript-runtime-client.js?hash=3755b87a9db33c177a60cfa7cbf41e1d9033df6f:53
> * base64.js?hash=faed986c6955587c13cda25dc9a4f102b9f22674:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
>   * at base64.js?hash=faed986c6955587c13cda25dc9a4f102b9f22674:17
>   * at base64.js?hash=faed986c6955587c13cda25dc9a4f102b9f22674:216
> * ejson.js?hash=8f5a52821d627c13f03f6c9f8691f2a0bc0831a4:17 Uncaught TypeError: Cannot read property 'Base64' of undefined
>   * at ejson.js?hash=8f5a52821d627c13f03f6c9f8691f2a0bc0831a4:17
>   * at ejson.js?hash=8f5a52821d627c13f03f6c9f8691f2a0bc0831a4:871
> * diff-sequence.js?hash=8eb896b9c63d4d9f25df3e753db9cb6e8b3af35f:17 Uncaught TypeError: Cannot read property 'EJSON' of undefined
>   * at diff-sequence.js?hash=8eb896b9c63d4d9f25df3e753db9cb6e8b3af35f:17
>   * at diff-sequence.js?hash=8eb896b9c63d4d9f25df3e753db9cb6e8b3af35f:302
> * geojson-utils.js?hash=9fb624fd53e827248a46955fc6a188dfe4f38306:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
>   * at geojson-utils.js?hash=9fb624fd53e827248a46955fc6a188dfe4f38306:17
>   * at geojson-utils.js?hash=9fb624fd53e827248a46955fc6a188dfe4f38306:438
> * id-map.js?hash=c9490b09a1a1d5375a52ce03119140ba81be8bf1:17 Uncaught TypeError: Cannot read property 'EJSON' of undefined
>   * at id-map.js?hash=c9490b09a1a1d5375a52ce03119140ba81be8bf1:17
>   * at id-map.js?hash=c9490b09a1a1d5375a52ce03119140ba81be8bf1:140
> * random.js?hash=4e647356c7e32999dba2a8addb95400243528bb0:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
>   * at random.js?hash=4e647356c7e32999dba2a8addb95400243528bb0:17
>   * at random.js?hash=4e647356c7e32999dba2a8addb95400243528bb0:343
> * mongo-id.js?hash=a1be6d230d8c489a687edf8bf9a64e520b34d3aa:17 Uncaught TypeError: Cannot read property 'EJSON' of undefined
>   * at mongo-id.js?hash=a1be6d230d8c489a687edf8bf9a64e520b34d3aa:17
>   * at mongo-id.js?hash=a1be6d230d8c489a687edf8bf9a64e520b34d3aa:163
> * ordered-dict.js?hash=d6e5219c163c4774a73956f410e7c2565d39634b:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
>   * at ordered-dict.js?hash=d6e5219c163c4774a73956f410e7c2565d39634b:17
>   * at ordered-dict.js?hash=d6e5219c163c4774a73956f410e7c2565d39634b:286
> * tracker.js?hash=5959317d7a0f1bc4d8f23ac6af69bd6d78e7b2ce:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
>   * at tracker.js?hash=5959317d7a0f1bc4d8f23ac6af69bd6d78e7b2ce:17
>   * at tracker.js?hash=5959317d7a0f1bc4d8f23ac6af69bd6d78e7b2ce:671
> * minimongo.js?hash=9ca66a0b51f0ab247c69fb7f1b9cbc8de221abaf:17 Uncaught TypeError: Cannot read property 'DiffSequence' of undefined
>   * at minimongo.js?hash=9ca66a0b51f0ab247c69fb7f1b9cbc8de221abaf:17
>   * at minimongo.js?hash=9ca66a0b51f0ab247c69fb7f1b9cbc8de221abaf:4797
> * check.js?hash=03574af9b5218423b2e7b6d9bae433f2573596f1:17 Uncaught TypeError: Cannot read property 'EJSON' of undefined
>   * at check.js?hash=03574af9b5218423b2e7b6d9bae433f2573596f1:17
>   * at check.js?hash=03574af9b5218423b2e7b6d9bae433f2573596f1:636
> * retry.js?hash=2d5eb7caf513b973780e0d80dbbdc0df16d6dd3a:17 Uncaught TypeError: Cannot read property 'Random' of undefined
>   * at retry.js?hash=2d5eb7caf513b973780e0d80dbbdc0df16d6dd3a:17
>   * at retry.js?hash=2d5eb7caf513b973780e0d80dbbdc0df16d6dd3a:105
> * callback-hook.js?hash=6a38b86e781d45ae0a606d2a6def910c47fe1d13:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
>   * at callback-hook.js?hash=6a38b86e781d45ae0a606d2a6def910c47fe1d13:17
>   * at callback-hook.js?hash=6a38b86e781d45ae0a606d2a6def910c47fe1d13:192
> * ddp-common.js?hash=96087f3a31518f03b650bc3a210af291022bd749:17 Uncaught TypeError: Cannot read property 'check' of undefined
>   * at ddp-common.js?hash=96087f3a31518f03b650bc3a210af291022bd749:17
>   * at ddp-common.js?hash=96087f3a31518f03b650bc3a210af291022bd749:517
> * reload.js?hash=1404b4f6c8537cfd3aab0f7ec0dc4bac698f60ea:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
>   * at reload.js?hash=1404b4f6c8537cfd3aab0f7ec0dc4bac698f60ea:17
>   * at reload.js?hash=1404b4f6c8537cfd3aab0f7ec0dc4bac698f60ea:255
> * socket-stream-client.js?hash=0a7102102e72089e1be37f8847071b4c13ee93a0:17 Uncaught TypeError: Cannot read property 'Retry' of undefined
>   * at socket-stream-client.js?hash=0a7102102e72089e1be37f8847071b4c13ee93a0:17
>   * at socket-stream-client.js?hash=0a7102102e72089e1be37f8847071b4c13ee93a0:532
> * ddp-client.js?hash=7fae7e488e45468ea4fda5047b1baf99d39dfd73:17 Uncaught TypeError: Cannot read property 'check' of undefined
>   * at ddp-client.js?hash=7fae7e488e45468ea4fda5047b1baf99d39dfd73:17
>   * at ddp-client.js?hash=7fae7e488e45468ea4fda5047b1baf99d39dfd73:2185
> * ddp.js?hash=dae39f35e2956c6df4d8b9963eea38371d546176:14 Uncaught TypeError: Cannot read property 'DDP' of undefined
>   * at ddp.js?hash=dae39f35e2956c6df4d8b9963eea38371d546176:14
>   * at ddp.js?hash=dae39f35e2956c6df4d8b9963eea38371d546176:23
> * allow-deny.js?hash=38f77ee2f5b9c7d3fe6074e68b10ac22cf390925:17 Uncaught TypeError: Cannot read property 'LocalCollection' of undefined
>   * at allow-deny.js?hash=38f77ee2f5b9c7d3fe6074e68b10ac22cf390925:17
>   * at allow-deny.js?hash=38f77ee2f5b9c7d3fe6074e68b10ac22cf390925:555
> * mongo.js?hash=0adba175af55a5540610d103c421dec2a6b2c022:17 Uncaught TypeError: Cannot read property 'AllowDeny' of undefined
>   * at mongo.js?hash=0adba175af55a5540610d103c421dec2a6b2c022:17
>   * at mongo.js?hash=0adba175af55a5540610d103c421dec2a6b2c022:868
> * reactive-var.js?hash=9f198731db45dae3de53bd7103e01e9421173e40:17 Uncaught TypeError: Cannot read property 'Tracker' of undefined
>   * at reactive-var.js?hash=9f198731db45dae3de53bd7103e01e9421173e40:17
>   * at reactive-var.js?hash=9f198731db45dae3de53bd7103e01e9421173e40:138
> * jquery.js?hash=e15504227515793c40a6a3a8ad340399cb657500:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
>   * at jquery.js?hash=e15504227515793c40a6a3a8ad340399cb657500:17
>   * at jquery.js?hash=e15504227515793c40a6a3a8ad340399cb657500:11100
> * reactive-dict.js?hash=8d78ca6e220b7078aa5ae76ea38c3fbe1f2641be:18 Uncaught TypeError: Cannot read property 'Tracker' of undefined
>   * at reactive-dict.js?hash=8d78ca6e220b7078aa5ae76ea38c3fbe1f2641be:18
>   * at reactive-dict.js?hash=8d78ca6e220b7078aa5ae76ea38c3fbe1f2641be:375
> * session.js?hash=0924da7b9d82f6c95b0c4eb141db786031915834:18 Uncaught TypeError: Cannot read property 'ReactiveDict' of undefined
>   * at session.js?hash=0924da7b9d82f6c95b0c4eb141db786031915834:18
>   * at session.js?hash=0924da7b9d82f6c95b0c4eb141db786031915834:94
> * akryum_vue.js?hash=3852e7ff0e0faf12f21ddffe3d7e435bb4786656:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
>   * at akryum_vue.js?hash=3852e7ff0e0faf12f21ddffe3d7e435bb4786656:17
>   * at akryum_vue.js?hash=3852e7ff0e0faf12f21ddffe3d7e435bb4786656:80
> * ongoworks_security.js?hash=9ab3bc6aa56f4e7a2d8966592bb0ae73913a2820:17 Uncaught TypeError: Cannot read property 'Mongo' of undefined
>   * at ongoworks_security.js?hash=9ab3bc6aa56f4e7a2d8966592bb0ae73913a2820:17
>   * at ongoworks_security.js?hash=9ab3bc6aa56f4e7a2d8966592bb0ae73913a2820:278
> * webapp.js?hash=7edac9184f1652211565c289897ec661ea5b14e2:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
>   * at webapp.js?hash=7edac9184f1652211565c289897ec661ea5b14e2:17
>   * at webapp.js?hash=7edac9184f1652211565c289897ec661ea5b14e2:67
> * autoupdate.js?hash=a2d41eedec64393031df5956eb5105b9ecfc0531:17 Uncaught TypeError: Cannot read property 'Tracker' of undefined
>   * at autoupdate.js?hash=a2d41eedec64393031df5956eb5105b9ecfc0531:17
>   * at autoupdate.js?hash=a2d41eedec64393031df5956eb5105b9ecfc0531:229
> * akryum_vue-component-dev-client.js?hash=8b0f61d3fe3955dc4bc1819354257eeecc619f49:17 Uncaught TypeError: Cannot read property 'Reload' of undefined
>   * at akryum_vue-component-dev-client.js?hash=8b0f61d3fe3955dc4bc1819354257eeecc619f49:17
>   * at akryum_vue-component-dev-client.js?hash=8b0f61d3fe3955dc4bc1819354257eeecc619f49:11872
> * akryum_vue-router2.js?hash=d08d8cb7318b0cdacd63fcfef7c00eac4f6e7d0e:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
>   * at akryum_vue-router2.js?hash=d08d8cb7318b0cdacd63fcfef7c00eac4f6e7d0e:17
>   * at akryum_vue-router2.js?hash=d08d8cb7318b0cdacd63fcfef7c00eac4f6e7d0e:136
> * livedata.js?hash=9ea2794795436b9e3896f3bcb0a59cc1e4bddc63:14 Uncaught TypeError: Cannot read property 'DDP' of undefined
>   * at livedata.js?hash=9ea2794795436b9e3896f3bcb0a59cc1e4bddc63:14
>   * at livedata.js?hash=9ea2794795436b9e3896f3bcb0a59cc1e4bddc63:27
> * global-imports.js?hash=cae987a497acd657b94b009fe9eb06396f89b6ef:3 Uncaught TypeError: Cannot read property 'Mongo' of undefined
>   * at global-imports.js?hash=cae987a497acd657b94b009fe9eb06396f89b6ef:3
> * app.js?hash=c6f87c11afa90fa88ac71f68e0ff803918269328:1 Uncaught ReferenceError: meteorInstall is not defined
>   * at app.js?hash=c6f87c11afa90fa88ac71f68e0ff803918269328:1

**Comment by mwarren2** [comment]
Did you run the following command?

`ln -s ../node_modules/quasar-framework imports`

**Comment by Noboxulus** [comment]
@mwarren2 yes, not the exact command tho as I am doing it on windows, I created the shortcut for ../node_modules/quasar-framework in imports folder.

The errors are the same before and after I created the shortcut.

**Comment by Noboxulus** [comment]
It appears creating a "windows" shortcut (eg: with the powershell command `powershell "$s=(New-Object -COM WScript.Shell).CreateShortcut('%cd%\imports\quasar-framework.lnk');$s.TargetPath='%cd%\node_modules\quasar-framework\';$s.Save()"
` doesn't work.
We would have to create a symlink using the cmd `mklink /D "imports\quasar-framework" "..\node_modules\quasar-framework\" instead.
`

**Comment by mwarren2** [comment]
Great. I’ll put that in the ReadMe
