### ISSUE TITLE
icons not showing up

### ISSUE THREAD

**Issue by tvogt** [quasarframework/quasar-template-meteor#26]
from impression as well as Quasar documentation, I assume that "icon=save/alarm/help/" in AppLayout.vue is supposed to be icons, not text.

Doesn't work, shows up as text for me.
Meteor 1.7.0.3
macOS

clean install from today.

**Comment by mwarren2** [comment]
I'm on holiday at the moment, I'll take a look Monday

**Comment by tvogt** [comment]
Doing a little more investigation, it first appeared that the public folder doesn't work. Directly accessing http://localhost:3000/MaterialIcons-Regular.woff lands me on the home page.

But then I spotted that the file is just a link, and the link is set wrongly:
# ls -lart public/
lrwxr-xr-x   1 tom  staff  119 22 Jun 09:32 MaterialIcons-Regular.woff -> /Users/malcolm/git/quasar-template-meteor/template/node_modules/quasar-extras/material-icons/MaterialIcons-Regular.woff

after fixing the link:
lrwxr-xr-x   1 tom  staff   71 23 Jun 08:00 MaterialIcons-Regular.woff -> ../node_modules/quasar-extras/material-icons/MaterialIcons-Regular.woff

it now works for me.

**Comment by mwarren2** [comment]
Well spotted. 
I'll correct the link.
