### ISSUE TITLE
Deploy Production on folder directory (`root/` or `template/`)

### ISSUE THREAD

**Issue by thearabbit** [quasarframework/quasar-template-meteor#27]
Which path that we base on `Build Production/Deployment`?
```
/root
  template/
    .deploy/
       mup.js
```
OR
```
template/
    .deploy/
       mup.js
```

**Comment by mwarren2** [comment]
Excuse the ignorance, but what is the /root folder?
I would have thought the second one was right.

I would like to help you, but unfortunately I don't know mup.js, I've never used it.

**Comment by thearabbit** [comment]
Thanks for your reply.
I will try myself
