### ISSUE TITLE
Could not use `this.$q.notify('Message')`!

### ISSUE THREAD

**Issue by thearabbit** [quasarframework/quasar-template-meteor#29]
Could not use `this.$q.notify('Message')`!
```
Error in event handler for "click": "TypeError: this.$q.notify is not a function"
```

**Comment by rstoenescu** [comment]
Hi,

<img width="198" alt="notify" src="https://user-images.githubusercontent.com/4665641/42618246-140c95a4-85bd-11e8-85b2-6534b28167c7.png">

Have you installed the Notify plugin in quasar.conf > framework > plugins?

**Comment by rstoenescu** [comment]
Ah, wait. Should get some sleep. I noticed just now that this is the Meteor repo. Sorry for closing. Disregard my previous message.

**Comment by thearabbit** [comment]
Thanks for very quick reply, I base on `Meteor`.
I used this example repo, and then tried to add `Notify`
```
// Home.vue
<q-btn @click="handleNotify">Notify</q-btn>
---
import {  Notify } from "/node_modules/quasar-framework/dist/quasar.mat.esm.js";
...
methods: {
    handleNotify() {
      this.$q.notify.... // don't work
      Notify.create('....'); // don't work
    }
  }
```
Main.js
```
...
import Quasar from '/node_modules/quasar-framework/dist/quasar.mat.esm.js';
//import Quasar from '/node_modules/quasar-framework/dist/quasar.ios.esm.js';

Vue.use(Quasar, {});

//App start
Meteor.startup(() => {
    const router = routerFactory.create();
    new Vue({
        router: router,
        render: h => h(AppLayout),
    }).$mount('app');
});
```
Could help me

**Comment by rstoenescu** [comment]
```js
import {  Notify } from "/node_modules/quasar-framework/dist/quasar.mat.esm.js"
Vue.use(Quasar, {
  plugins: [ Notify ]
})
```

**Comment by thearabbit** [comment]
It work fine, But I not clear how to use  
```
framework: {
  plugins: ['Notify']
}
---
framework: {
  components: ['QField']
}
```
What it mean???

**Comment by thearabbit** [comment]
could I use global `component and plugins`?
Like Other UI Framework: `Element UI, Vuetify...` 
```
Vue.use(UI-Framework)
```

**Comment by thearabbit** [comment]
Could I use config `plugins` in vue template like `components`
```js
export default {
  components: {
    QList,
    QListHeader,
    QBtn,
  },
  plugings: [Notify]
```

**Comment by letuan0803** [comment]
> Hi,
> 
> <img alt="notify" width="198" src="https://user-images.githubusercontent.com/4665641/42618246-140c95a4-85bd-11e8-85b2-6534b28167c7.png">
> 
> Have you installed the Notify plugin in quasar.conf > framework > plugins?

thank you. it work for me!!!
