### ISSUE TITLE
QCollapsible shows literal "arrow_drop_down" instead of the drop down arrow picture

### ISSUE THREAD

**Issue by Noboxulus** [quasarframework/quasar-template-meteor#30]
Please refer to the images below.

Expected (taken from [quasar components:](https://quasar-framework.org/components/collapsible.html)

> ![image](https://user-images.githubusercontent.com/19311003/42737361-9de67e5e-88a4-11e8-843c-882beb2c5aa6.png)

> ![image](https://user-images.githubusercontent.com/19311003/42737366-b9abda58-88a4-11e8-8074-040c3da6fb89.png)

Actual:
>![image](https://user-images.githubusercontent.com/19311003/42737264-c42bd998-88a3-11e8-985c-780e8cd48bc1.png)

>![image](https://user-images.githubusercontent.com/19311003/42737279-f194403c-88a3-11e8-9e0b-1174052ced07.png)

The code snippet I added to `Home.vue`:
>![image](https://user-images.githubusercontent.com/19311003/42737507-a6558894-88a6-11e8-9557-194afc68d478.png)

I am using windows for this.

I tried making a link to quasar-extras in imports folder just like what we did for quasar-framework, but it doesn't work.
The cmd I used: `mklink /D "imports\quasar-extras" "..\node_modules\quasar-extras\"`

Could this be related to the readme snippet below?
> On Windows you will probably also have to make the link in the /public folder to the Material Icons .woff file work properly. 

If so, can I know which folder I should link to which folder?

Thanks.

>

**Comment by mwarren2** [comment]
You need a link from the /public folder to:
../node_modules/quasar-extras/material-icons/MaterialIcons-Regular.woff

**Comment by Noboxulus** [comment]
I just tried it, it works!
Thank you.
You'd have to remove or rename the existing `public\MaterialIcons-Regular.woff`
Then you run this cmd `mklink "public\MaterialIcons-Regular.woff" "..\node_modules\quasar-extras\material-icons\MaterialIcons-Regular.woff"`.
(without the /D argument since it is not a directory)
