### ISSUE TITLE
How should I correctly include a Quasar Plugin?

### ISSUE THREAD

**Issue by Billybobbonnet** [quasarframework/quasar-template-meteor#32]
Hello,

First, thank you for this integration. I used it as a base for an app I'm just starting to work on, and this is my first vue experience.

I added a calendar plugin (https://github.com/stormseed/quasar-calendar) to this app. Since I could not import directly the node package, I copied its content in the `template/imports` folder, updated the imports paths to Quasar accordingly to the path used in this repo, and updated ``@import '~variables' to `@import '~node_modules/quasar-framework/dist/quasar.mat.styl'`

If I try to include the npm as they suggest in the plugin readme, I get a `SyntaxError: export declarations may only appear at top level of a module`.

Is there a way to include this package without having to (1) include its files in the codebase and (2) edit the files import paths?

**Comment by mwarren2** [comment]
I wish I could help you.

It took a long time to get **quasar-framework** working with Meteor and I know that what we did to make it work is not perfect, but for the moment it's the best we've got....

**Comment by Billybobbonnet** [comment]
I'll close this issue. Feel free to reopen it if you find a more suitable way to include that plugin (and similar ones).
