### ISSUE TITLE
What difference import `/node_modules/quasar-framework/dist/...` VS `/imports/quasar-framework/dist/...`

### ISSUE THREAD

**Issue by thearabbit** [quasarframework/quasar-template-meteor#35]
What difference import `/node_modules/quasar-framework/dist/...` VS `/imports/quasar-framework/dist/quasar.mat.esm.js`?
Which one we should use?

**Comment by mwarren2** [comment]
Well the second one is just a link that points to the first one, so I would use the first one.

**Comment by thearabbit** [comment]
But now I tried import without `node_modules`, It still work fine
```
import {...} from 'quasar-framework/dist/quasar.mat.esm.js'
```
So I should be use this???
