### ISSUE TITLE
Load/refresh page don't smooth!

### ISSUE THREAD

**Issue by thearabbit** [quasarframework/quasar-template-meteor#38]
The page don't smooth when loading/refresh???
(Show page don't has style)

![sep-04-2018 20-20-47](https://user-images.githubusercontent.com/4495160/45034037-821c5f00-b080-11e8-8413-ef050aad9918.gif)

**Comment by mwarren2** [comment]
Hi,
That's a question you need to put in the Quasar forums or on StackOverflow.

It's not something I know much about!

**Comment by thearabbit** [comment]
Thanks, now I open new on `quasar forums`.

**Comment by mwarren2** [comment]
Though I have always noticed this written in the developer's console when I'm at localhost:3000 in the browser:

> You are currently in development mode. If the Hot-Module-Replacement system is enabled (`on` by default), the CSS will be injected to the page after the scripts are loaded. This may result in Flash Of Unstyled Contents. Those will not occur in production.

**Comment by thearabbit** [comment]
Thanks again, I will try to run in Production mode.

![image](https://user-images.githubusercontent.com/4495160/45034537-01f6f900-b082-11e8-93b9-f4401672e1a1.png)
