### ISSUE TITLE
Could install `quasar` via NPM, and use `import.....`?

### ISSUE THREAD

**Issue by thearabbit** [quasarframework/quasar-template-meteor#4]
I base on `Meteor + Vue-Meteor` (newbie for Vue).
Why don't install `quasar` via NPM, and use `import.....`?

**Comment by mwarren2** [comment]
It would be very nice if we could use the npm install.
Unfortunately quasar uses webpack, and meteor doesn't.

So after a lot of trying I had to abandon the npm install, which was very unfortunate.
However Meteor 1.5 may well have a solution, and I will be trying the latest beta as soon as that is possible.

But at the moment I have an open bug with akryum:vue-component so I am blocked for a while, and cannot install 1.5

**Comment by thearabbit** [comment]
Thanks, waiting to try

**Comment by mwarren2** [comment]
Unfortunately Meteor 1.5 hasn't solved the problem.

There's an open issue about this, which we will just have to hope is high enough on the list to be solved soon.

**Comment by mwarren2** [comment]
@thearabbit This has been assigned a [feature request at Meteor](https://github.com/meteor/meteor-feature-requests/issues/6), and seems to be followed by several people. So it's got a fairly good chance of being done soon.

**Comment by mwarren2** [comment]
@thearabbit I've solved this and it now installs from npm. 

A little file called 

> .vueignore

 was needed in the root folder to ignore .vue files when compiling. 
You can read about it [on this page](https://github.com/meteor-vue/vue-meteor/tree/master/packages/vue-component)

So I am closing this.

**Comment by thearabbit** [comment]
Look great, I will try soon 👍
