### ISSUE TITLE
Upgraded to Meteor 1.8, but waiting for akryum:vue-router2 fix

### ISSUE THREAD

**Issue by mwarren2** [quasarframework/quasar-template-meteor#40]
Unfortunately due to a [problem with akryum:vue-router2](https://github.com/meteor-vue/vue-meteor/issues/336) we are unable to upgrade to Meteor 1.8

It doesn't seem to be a difficult problem to solve (let's hope not), we can only wait and hope that it will be dealt with soon.

**Comment by rekDen** [comment]
Hey mwarren2,

my team mate @ahmelkady and me figured it out how to solve this issue.
For us the problem was solved when downgrading akryum_vue-router2 from 0.2.2 to 0.2.0 by changing manually the .meteor/versions file.

Best regards

**Comment by mwarren2** [comment]
In order to move things forward I guess I can just replace akryum:vue-router2 with vue-router2. I haven't done anything here that actually needs the akryum version.

**Comment by mwarren2** [comment]
Replaced akryum:vue-router2 with vue-router.
