### ISSUE TITLE
Quasar 1.0 is released!!!!!!!!

### ISSUE THREAD

**Issue by thearabbit** [quasarframework/quasar-template-meteor#41]
Quasar 1.0 is released!!!!!!!!

https://medium.com/quasar-framework/quasar-1-0-reaching-for-the-stars-284e7716625a

**Comment by thearabbit** [comment]
I tried, but get error
```js
import Quasar from 'quasar'
------------------------
Uncaught Error: Cannot find module 'quasar'
    at makeMissingError (modules-runtime.js?hash=d3c3e5d67c95f97a60888bda7373292efad3be5e:232)
    at Module.require (modules-runtime.js?hash=d3c3e5d67c95f97a60888bda7373292efad3be5e:251)
    at Module.moduleLink [as link] (modules.js?hash=235183ca901a1e5610984473a56483095ea17662:285)
    at main.js (main.js:1)
    at fileEvaluate (modules-runtime.js?hash=d3c3e5d67c95f97a60888bda7373292efad3be5e:346)
    at Module.require (modules-runtime.js?hash=d3c3e5d67c95f97a60888bda7373292efad3be5e:248)
    at require (modules-runtime.js?hash=d3c3e5d67c95f97a60888bda7373292efad3be5e:268)
    at app.js?hash=c6c5b9e948103b389f4f2ea5ebdac249dc26f90e:260
```

**Comment by rstoenescu** [comment]
Hi @mwarren2 ! Please connect with me to help get this bumped to 1.0. Thanks!

**Comment by mwarren2** [comment]
@rstoenescu @thearabbit I've got urgent work to do today, I'll be in contact as soon as I can look at this

**Comment by rstoenescu** [comment]
@mwarren2 No rush. At your own pace. I'll be available for you.

**Comment by thearabbit** [comment]
Very thanks for all 💯.
Waiting you...

**Comment by mwarren2** [comment]
@thearabbit How did you update to the beta?

I would like very much to try the beta, but I'm not keen on updating here unless it's easy for other people to do so. The beta isn't on npm.

**Comment by thearabbit** [comment]
Quasar changed npm name on `1.0`.
```js
// package.json
{
  "name": "meteor-quasar1",
  "private": true,
  "scripts": {
    "start": "meteor run",
    "test": "meteor test --once --driver-package meteortesting:mocha",
    "test-app": "TEST_WATCH=1 meteor test --full-app --driver-package meteortesting:mocha",
    "visualize": "meteor --production --extra-packages bundle-visualizer"
  },
  "dependencies": {
    "@babel/runtime": "^7.1.5",
    "@quasar/extras": "^1.0.0",
    "lodash": "^4.17.11",
    "meteor-node-stubs": "^0.4.1",
    "quasar": "^1.0.0-beta.0",
    "vue": "^2.6.4",
    "vue-router": "^3.0.2",
    "vuex": "^3.1.0"
  },
  "meteor": {
    "mainModule": {
      "client": "client/main.js",
      "server": "server/main.js"
    },
    "testModule": "tests/main.js"
  }
}
```

**Comment by thearabbit** [comment]
### main.js
```js
.......
/ Quasar globally
import '@quasar/extras/material-icons/material-icons.css'
import 'quasar/dist/quasar.min.css'
import Quasar from 'quasar/dist/quasar.esm.js' // work fine
import langEn from 'quasar/lang/en-us'

// import Quasar  from 'quasar' // don't work
// import { Quasar } from 'quasar/dist/quasar.esm.js' // don't work (don't want to declare with globally)
// import Quasar from 'quasar/dist/quasar.umd.min.js' // don't wrok


Vue.use(Quasar, {
  lang: langEn,
})
......
```

**Comment by mwarren2** [comment]
Ah, so it's been renamed to **quasar** from quasar-framework, that explains it

**Comment by thearabbit** [comment]
I am not sure

![image](https://user-images.githubusercontent.com/4495160/52601355-1214cf00-2e91-11e9-8d07-1fe409d71584.png)

**Comment by thearabbit** [comment]
![image](https://user-images.githubusercontent.com/4495160/52602448-50ac8880-2e95-11e9-99c6-d6c1a4222993.png)

**Comment by nothingismagick** [comment]
@mwarren2 - I highly recommend you visit the discord channel and join the conversation. You are always welcome!

**Comment by thearabbit** [comment]
Could you join this issue on `Meteor`?
https://forums.meteor.com/t/get-error-import-quasar-from-quasar-1-0/47821/3

**Comment by mwarren2** [comment]
@thearabbit A little patience, I haven't actually been able to look at it, I've got a lot on my plate.
I'll be trying it out in the next couple of days

**Comment by thearabbit** [comment]
No problem

**Comment by mwarren2** [comment]
@thearabbit I've got Quasar 1.0.0 working, but there are many, many breaking changes to the ui, so this is going to take a while.

**Comment by thearabbit** [comment]
Haha, working on `import Quasar from 'quasar'`?

**Comment by nothingismagick** [comment]
@mwarren2 - there is a worksheet about this that the core team has been putting together with some of our early adopters: https://gist.github.com/hawkeye64/da4b4d662ab1484bd0b532ffd871679e

**Comment by mwarren2** [comment]
@rstoenescu I have a problem with QLayout in the beta for some reason.
I've tried to install the beta both for this template and for a larger project of mine, and I just get a blank div with QLayout.

Problem is, I haven't been able to work out what on earth is happening. I haven't been able to debug this at all. 

QLayout is basically just a black hole in my apps, where components never appear. If I place them outside of QLayout they appear.

Whatever I place inside QLayout never figures in the raw html and all I ever see are two lines of empty comments - which I did not put there.

```
<div data-v-560dfbe2="" class="q-layout shadow-2 rounded-borders">
    <!----><!---->
</div>
```

I've spent a lot of time trying to see where I may have gone wrong, but I have come up blank.

**Comment by rstoenescu** [comment]
@mwarren2 Haven't looked at what Vue version you are using, but you need 2.6.x. This is probably why the default slot is not being correctly detected in your case. Let me know if this is not the issue.

**Comment by mwarren2** [comment]
@rstoenescu Thanks, that solved it

**Comment by mwarren2** [comment]
Ok, update to 1.0.0 beta is ok.

However I'll try an install on IOS for good measure

**Comment by thearabbit** [comment]
💯

**Comment by thearabbit** [comment]
Now It work fine for directly importing, don't use `ln -s ../node_modules/quasar imports`
```js
// main.js
import "@quasar/extras/material-icons/material-icons.css";
import "quasar/dist/quasar.min.css";
import { Quasar } from "quasar";
import langEn from "quasar/dist/lang/en-us.umd.min.js";
Vue.use(Quasar, {
  lang: langEn
});
```
I base on `METEOR@1.8.1, "quasar": "^1.0.0-beta.18"`

**Comment by mwarren2** [comment]
Yes, the short Quasar import now works, which is great
`import { Quasar } from "quasar";`

But I have been unable to remove the link in the **/imports** folder to quasar. If I remove that, nothing works.
The same with the link in the **/public** folder to 'web-fonts', it has to be there.

I'll install the update with the latest beta soonest, later today.
