### ISSUE TITLE
please use yarn.lock and not package-lock.json

### ISSUE THREAD

**Issue by nothingismagick** [quasarframework/quasar-template-meteor#42]
In compliance with the rest of the repositories in the Quasar ecosystem, please create and commit a yarn.lock file & remove the package.json

**Comment by mwarren2** [comment]
um, what you're saying is you want me to give up npm and convert to yarn, which I've never used.
Well, I'll have to look into it I suppose.

But this isn't really part of the Quasar ecosystem. For a start if you use Meteor you don't/can't use Webpack.

**Comment by rstoenescu** [comment]
@mwarren2 Leave package.json if this is what you are most proficient with. We'll work around this.

**Comment by nothingismagick** [comment]
For some background info: I am preparing automatic auditing of our repositories and all of them use yarn and we commit the yarn.lock file - but as Razvan said, we'll work around it. Your project is awesome!
