### ISSUE TITLE
TypeError: null is not an object (evaluating 'document.body.classList')

### ISSUE THREAD

**Issue by mwarren2** [quasarframework/quasar-template-meteor#43]
@rstoenescu I get this error from the installed app on IOS.

> TypeError: null is not an object (evaluating 'document.body.classList')

I've already seen this error on another app I've been working on for a while, and I think this appeared before the 1.0.0 beta, in 0.17.  I just hadn't had time to follow it up at the time.

It happens on **line 41 in body.js** in the bodyInit() function
`document.body.classList.add.apply(document.body.classList, cls)`

**Comment by rstoenescu** [comment]
@mwarren2 Is this code run on the server? If on a browser, this definitely cannot fail. If running on the server, then there's a guard already in place which checks for `window` global. Is that by any chance defined in Meteor on the server side?

**Comment by mwarren2** [comment]
@rstoenescu This is client side, not SSR if that's what you mean.

**Comment by rstoenescu** [comment]
What iOS version are we talking about? `document.body` is supported by all browsers, `classList` is again supported by all browsers.

**Comment by rstoenescu** [comment]
Means you're placing the Quasar script in the head and not body? So `body` is not available yet. Need more details unfortunately.

**Comment by mwarren2** [comment]
Meteor deals with placement of the code.
It's all .js code and it's all in the head on the phone.

However given what you've told me I reckon it needs to be solved by Meteor, and I've got a couple of ideas I can look into.

**Comment by mwarren2** [comment]
Found it.

Thanks for the really fast response, as always !
