### ISSUE TITLE
image locations

### ISSUE THREAD

**Issue by mehmetulukaya** [quasarframework/quasar-template-meteor#47]
Hello,

I couldn't successful about to get images on the localhost directory like as "/statics/logo.png" but I can show the "https://placeimg.com/500/300/nature?t=" similar images.
What should I do to show local images on the page?

Working template:

```
  <q-img
      src="https://image.flaticon.com/icons/svg/24/24509.svg"
      spinner-color="white"
      style="height: 140px; max-width: 150px"
    />
	

```
but this is not working:

```
   <q-img
      src="~/statics/24509.svg"
      spinner-color="white"
      style="height: 140px; max-width: 150px"
    />

```
I changed the       src="~/statics/24509.svg" to       src="/statics/24509.svg" or       src="../../statics/24509.svg"

but not worked.

Note: Also I tried to `<img>` tag to 

Thanks in advance.

**Comment by mwarren2** [comment]
Place the image in the **public** folder and then you can reference it like this:
 
`       <q-img
                src="/220px-Merope.jpg"
                style="height: 140px; max-width: 150px"
        />
`

I will add this image to the code in a couple of minutes

**Comment by mwarren2** [comment]
Can we close this?
