### ISSUE TITLE
Could you example to manage user authentication on login/logout form?

### ISSUE THREAD

**Issue by thearabbit** [quasarframework/quasar-template-meteor#49]
Could you example to manage user authentication on login/logout form?

Thanks for your example!

**Comment by mwarren2** [comment]
I'd refer you to the extensive Meteor documentation on the subject, because whether you have Quasar or not makes no real difference to using Meteor's user authentication

**Comment by thearabbit** [comment]
thanks for your reply.
I will check Meteor User account.
If you can, please share me.
