### ISSUE TITLE
Infinite Scroll Second Parameter is undefined

### ISSUE THREAD

**Issue by nigeltiany** [quasarframework/quasar-template-meteor#7]
Mapping a vuex actions
```javascript
...mapActions('namespace',[
    'theLoadingAction'
])
```
And having the action at the store make the request
```javascript
actions: {
   theLoadingAction({state,commit},index,done){
       console.log(index); //works well and counts for each request made
       console.log(done); //is always undefined 
   }
}
```
Returns undefined for the second argument

The action is mapped this way to  the component
```html
<q-infinite-scroll :handler="theLoadingAction">
</q-infinite-scroll>
```

Quasar Version: 0.13.9

**Comment by nigeltiany** [comment]
Maybe there is something i missed about JS :-) 
Changing [this line if code](https://gist.github.com/nigeltiany/dfdfb4d47027c3a95f19c048700f8828#file-fixquasarinfinitescroll-js-L129) still result in 
```
quasar
```
```
undefined
```

**Comment by mwarren2** [comment]
quasar-template-meteor is only about getting quasar-framework to work with meteor.
You are asking a question about something very specific in quasar that I don't have the necessary knowledge to answer.

So I am closing this. - Perhaps you should ask this in the [quasar forums](forum.quasar-framework.org)?

**Comment by nigeltiany** [comment]
No I'm reporting a bug. The forums are for usage questions. Please reopen
or reference this in the main quasar framework repository

**Comment by mwarren2** [comment]
The main quasar framework repository is [here](https://github.com/quasarframework/quasar)

**Comment by nigeltiany** [comment]
I chose to open it here because it might work as expected on the main
repository

**Comment by mwarren2** [comment]
That's fine that you've opened it here, but I'm not qualified to answer your question.
I would certainly help you if I could.

You would need to create a test-app with all the ingredients showing the problem and apply to the main repository, though.

**Comment by nigeltiany** [comment]
Okay, I'll do that.
