### ISSUE TITLE
How to create a custom theme file

### ISSUE THREAD

**Issue by samuelandert** [quasarframework/quasar-template-meteor#9]
Thank you very much for this boilerplate!
How do I create a custom theme .styl file for example for the desktop/web variation, in order to globally override the stylus variables. 
I would like to spice up the standard desktop/web theme, which we would include here: 
`
else {
            //default
            require('/imports/quasar/quasar.MyCustomDesktopTheme.styl');
        }
`

**Comment by mwarren2** [comment]
@samuelandert Sorry for my late reply... 
Unfortunately .styl files are beyond my current capabilities. I can't help much with this.

However I expect that the forums would be a good place to go for advice. 
Sorry if that's not much help!
